---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
stringData:
  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQD9zu9ePGYqLhAAUV7aHgdETMxJv6ncrLsFow== 

