---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: base
spec:
  serviceName: base
  replicas: 1
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      labels:
        app: base
    spec:
      initContainers:
      - image: k8s.gcr.io/busybox
        name: touch-file
        command: [ "sh", "-c"]
        args:
          - touch "/data/$(hostname).$(date)"
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - image: k8s.gcr.io/busybox
        name: node-name
        command: [ "sh", "-c"]
        args:
        - while true; do
            echo -en '\n';
            date;
            ls /local;
            sleep 10;
          done;
        volumeMounts:
          - name: data
            mountPath: /local
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-storage
